name: CI-cmake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir -p build && cd build && cmake ..
    - name: build
      run: cd build && make
    - name: test
      run: cd build && ctest
